databases:
  - name: news-site-db
    plan: free

services:
  - type: web
    name: news-site
    env: node
    plan: free
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npx prisma db push && npx next start -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        fromDatabase:
          name: news-site-db
          property: connectionString
      - key: DEEPSEEK_API_KEY
        sync: false

